### ISSUE TITLE
reaxt not found in Phoenix

### ISSUE THREAD

**Issue by collin** [awetzel/reaxt#4]
Adding reaxt to a Phoenix app and starting the server results in this error:

```
** (File.Error) could not read file web/node_modules/reaxt/package.json: no such file or directory
    (elixir) lib/file.ex:245: File.read!/1
    lib/tasks.ex:44: Mix.Tasks.Compile.ReaxtWebpack.run/1
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (mix) lib/mix/tasks/compile.all.ex:15: Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.ex:64: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:251: Mix.Task.run_task/3
```

I poked around and found the `commonjs_reaxt/` directory.

I was able to clear up this error message by this action:

```
cd path-to-commonjs_reaxt/
npm link
cd path-to-phoenix-app/web/ # where webpack.conf.js lives
npm link reaxt
```

Now node seems to be able to find reaxt and things move along.

This works for development, but isn't ideal. Any hunches as to what might be going wrong?

**Comment by awetzel** [comment]
Hello collin, actually the compiler `:reaxt_webpack` should do the "npm install /path/to/reaxt/priv/commonjs_reaxt" if the js reaxt lib is not found and that the installed version differs from the reaxt version. 
See
https://github.com/awetzel/reaxt/blob/master/lib/tasks.ex#L39-L53

Maybe you forgot to add the compiler ?

**Comment by awetzel** [comment]
to add the compiler, add `compilers: [:reaxt_webpack | Mix.compilers]` to your `mix.exs`
